### ISSUE TITLE
Building with ndk requires typedef for false 

### ISSUE THREAD

**Issue by ghost** [saurik/mempodroid#1]
Running current Debian Unstable with current Android ndk. Made a simple AndroidManifest.xml and Android.mk to do a BUILD_EXECUTABLE. The ndk does not appear to include bool.h, so I added one line to get it to build.

```
typedef enum { false, true } bool;
```

Don't know if it is an "issue" exactly, but it someone else is kicking this around they may run into it.

**Comment by saurik** [comment]
Thanks! I didn't notice as, despite having written this in C (which I sometimes do for code I'm intending to mostly throw away at other people), my build environments are all nigh-unto hardcoded to use g++ (which apparently ignored the file extension ;P). The correct fix is to #include &lt;stdbool.h&gt;: I have pushed the change.
